apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich-db
resources:
- postgres-namespace.yaml
- postgres-configmap.yaml
- postgres-secret.yaml
- postgres-statefulset.yaml
- postgres-service.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: immich-stack
