apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: immich-db
spec:
  ports:
  - port: 5432
    targetPort: postgres
  selector:
    app: postgres
  clusterIP: None # Headless service for StatefulSet
