apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # Or your Minikube default
  resources:
    requests:
      storage: 800Gi # Adjust based on your expected library size
