apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
  namespace: immich-app
type: Opaque
data:
  # Replace with your Base64 encoded PostgreSQL password
  DB_PASSWORD: VHNlZW5hb3BzY2QgLi4v
  # Replace with your Base64 encoded JWT_SECRET
  JWT_SECRET: ZjA4MTMxNmYyZWYzMTllYWRhZjJkY2NhNzJiNTdkMTAzN2RiMzg4ODg2NzMwNjJiZTQ0N2YzMjY0YmQwNGYxNA== # e.g., MTRkZjI3Y...
  # Add other secrets like ADMIN_EMAIL, ADMIN_PASSWORD if Immich supports them for initial setup
  # For S3 (optional, covered later)
  # S3_ACCESS_KEY_ID: ""
  # S3_SECRET_ACCESS_KEY: ""
